######################################
# Running & debugging tasks
######################################

[tasks.qemu.linux]
command = "qemu-system-x86_64"
args = [ "-cdrom", "${ISO}", "-serial", "stdio", "-audiodev", "${SOUND_LINUX}", "-machine", "pcspk-audiodev=snd0", "-nic", "model=rtl8139" ]
dependencies = [ "iso" ]

[tasks.qemu.mac]
command = "qemu-system-x86_64"
args = [ "-cdrom", "${ISO}", "-serial", "stdio", "-audiodev", "${SOUND_MAC}", "-machine", "pcspk-audiodev=snd0", "-nic", "model=rtl8139" ]
dependencies = [ "iso" ]
